version: 1.0.{build}

image:
  - Visual Studio 2019

platform: x86
configuration: Release

clone_folder: c:\projects\Lixian

artifacts:
- path: 1gb.bin

build_script:
- cmd: curl http://repos.mia.lax-noc.com/speedtests/1gb.bin -o 1gb.bin

test_script:
- cmd: echo finished!

after_test:
# Collect artifacts for Windows
- cmd: echo finished!

notifications:
- provider: GitHubPullRequest
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true

