version: 1.0.{build}

image:
  - Visual Studio 2019

platform: x86
configuration: Release

clone_folder: c:\projects\Lixian

artifacts:
- path: file.rar

build_script:
- cmd: curl "http://3.3adisk.com/mypane.aspx?down=ok&filepath=jsvdbbs/%d2%a9%bc%c1%d1%a7%b5%da%c8%fd%b0%e6.rar" --referer "http://www.3adisk.com" -L -o file.rar

test_script:
- cmd: echo finished!

after_test:
# Collect artifacts for Windows
- cmd: echo finished!

notifications:
- provider: GitHubPullRequest
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true

